# based on https://medium.com/chrisrbailey/github-actions-using-postgres-postgis-and-psql-e920a2aea7e1
name: Generate JSON tiles
on:
  workflow_dispatch:
jobs:
  run:
    name: Generate JSON tiles
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_PASSWORD: password
          POSTGRES_DB: osm
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install dependencies
        run: |
          sudo apt install osmium-tool
          sudo mkdir -p /ingest/imposm3 && wget -q -O - https://github.com/omniscale/imposm3/releases/download/v0.11.1/imposm-0.11.1-linux-x86-64.tar.gz | tar -xz --strip-components=1 -C /ingest/imposm3
          pip install pyrosm
      - name: Download pbf
        run: |
          python -c "from pyrosm import get_data; fp = get_data('Monaco'); print(fp)"
          osmium fileinfo /tmp/pyrosm/Monaco.osm.pbf
      - name: Import pbf
        run: |
          imposm import -mapping config.mapping -write -connection postgresql://postgres@localhost/osm -srid 4326 -cachedir cache/
