# based on https://medium.com/chrisrbailey/github-actions-using-postgres-postgis-and-psql-e920a2aea7e1
name: Generate JSON tiles

on:
  workflow_dispatch:
    inputs:
      pbf_url:
        description: URL of OSM PBF file
        required: true
        default: http://download.geofabrik.de/north-america/us/district-of-columbia-latest.osm.pbf

env:
  PBF_LINK: ${{ github.event.inputs.pbf_url }}
  PBF_PATH: /tmp/region.osm.pbf

jobs:
  run:
    name: Generate JSON tiles
    runs-on: ubuntu-latest
    env:
      POSTGRES_DSN: postgresql://postgres:password@localhost/osm 

    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_PASSWORD: password
          POSTGRES_DB: osm
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout openscape
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo mkdir -p /ingest/imposm3
          sudo chmod -R a+rw /ingest
          wget -q -O - https://github.com/omniscale/imposm3/releases/download/v0.11.1/imposm-0.11.1-linux-x86-64.tar.gz | \
            tar -xz --strip-components=1 -C /ingest/imposm3
          pip install psycopg2
      - name: Download + import pbf
        run: |
          wget -q -O $PBF_PATH $PBF_LINK
          psql -d $POSTGRES_DSN -c "CREATE EXTENSION IF NOT EXISTS hstore"
          /ingest/imposm3/imposm import \
            -mapping svcs/data/soundscape/other/mapping.yml \
            -read $PBF_PATH -srid 4326 -dbschema-import="public" \
            -write -connection postgis://postgres:password@localhost/osm  \
      - name: Install PostGIS functions
        run: |
          wget -q -O - https://raw.githubusercontent.com/mapbox/postgis-vt-util/master/postgis-vt-util.sql | \
            psql -d $POSTGRES_DSN
          psql -d $POSTGRES_DSN -f svcs/data/tilefunc.sql
          psql -d $POSTGRES_DSN -f svcs/data/getTiles.sql
      - name: Generate tiles
        run: |
          psql -d $POSTGRES_DSN -t -A -F"," -c "select * from getAll16Tiles()" | \
            python svcs/data/make_static_tiles.py /tmp/tiles/ $POSTGRES_DSN
